packages/migrator/readme.md, packages/migrator/src/index.ts, packages/migrator/test/cli.test.ts
This avoids adding umzug-specific data in the api surface.
=> fix(migrations): only return `file` and `path` properties

packages/demo/migrations/2020-04-06T01-19.message-priority.sql, packages/demo/migrations/down/2020-04-06T01-19.message-priority.sql, packages/demo/src/generated/db/Message.ts, packages/demo/src/generated/db/_pg_types.ts, packages/typegen/src/index.ts, packages/typegen/test/generated/main/Bar.ts, packages/typegen/test/generated/main/_pg_types.ts, packages/typegen/test/generated/with-custom-date/_pg_types.ts, packages/typegen/test/generated/with-date/_pg_types.ts, packages/typegen/test/index.test.ts
fixes https://github.com/mmkal/slonik-tools/issues/163
Hand-written `typeMappers` are no longer required for postgres enums, e.g.:
```sql
create type abc as enum('foo',  'bar')
```
The above will automatically translate to a typescript [string literal type](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types) of `'foo' | 'bar'`.
=> feat(enums): auto generate enum types

package.json, packages/migrator/package.json, packages/migrator/readme.md, packages/migrator/src/index.ts, packages/migrator/test/cli.test.ts, packages/migrator/test/migrations/2000-01-03T00-00.three.js, packages/migrator/test/migrations/2000-01-04T00-00.four.ts, readme.md, yarn.lock
fixes https://github.com/mmkal/slonik-tools/issues/45 and https://github.com/mmkal/slonik-tools/issues/141
=> feat: javascript and typescript migrations

packages/migrator/src/index.ts, packages/migrator/test/migrations.test.ts
The following changes will allow you to target a different schema as the default one (`public`).
We currently use `@slonik/migrator` in a bunch of projects but have had to patch it with this change to allow us to target a different schema to create the migrations table in. Our data is split up in different schemas and different entities have granular control over their own schema. We also wanted the migrator to only put the migrations specific to that schema in the same schema. This ment making sure we can target the schema when we create the migrations table.
Because `migrationsTableName` is being run through `sql.identifier` it was impossible to pass something like `otherschema.migration`.
This change opens up `migrationsTableName` to be an array so it can be passed to `sql.identifier` …
=> feat: allow migrations table to be created  in different schema

packages/typegen/src/index.ts
=> fix: don't try to import non-typescript files

packages/migrator/package.json, packages/migrator/src/index.ts, packages/migrator/types/slonik-sql-tag-raw.d.ts, yarn.lock
slonik-sql-tag-raw has a bug and also does unnecessary processing of queries for this use case. And it's simpler to just return a query object.
=> chore: drop slonik-sql-tag-raw

packages/migrator/src/index.ts, packages/migrator/test/generated/locking_test/singelTransaction/migrations/down/m1.sql, packages/migrator/test/generated/locking_test/singelTransaction/migrations/m1.sql, packages/migrator/test/generated/locking_test/singelTransaction/migrations/m2.sql, packages/migrator/test/generated/run/migrations/04.four.ts, packages/migrator/test/locking.test.ts, packages/migrator/test/pool-helper.ts, packages/migrator/test/script-migrations.test.ts
Failing migrations when using `singleTransaction: true` could cause errors when trying to release the advisory lock. This fixes that, and also creates a dedicated connection for locking/unlocking to avoid warnings about a different session unlocking, under normal circumstances.
Implementation:
This overrides the `runCommand` method of `Umzug` rather than relying on `beforeCommand` and `afterCommand` events (for locking). This allows keeping the whole command in scope to easier use `pool.connect`. As a follow-up, it may be possible to stop using the events entirely.
=> Lock transaction fix

packages/migrator/package.json, packages/migrator/readme.md, packages/migrator/src/index.ts, packages/migrator/test/generated/repair_test/01.one.sql, packages/migrator/test/generated/repair_test/down/01.one.sql, packages/migrator/test/repair.test.ts, yarn.lock
The hash function was broken in commit 9076eea686665b51d5e06362b99e1d1fb48a778f (first released in `v0.8.0`), since then the file name was used as hash.
I restored the hash calculation to the original version.
https://github.com/mmkal/slonik-tools/blob/3be1370c98f1985c1fd921f38408730b5d7d78ec/packages/migrator/src/index.ts#L176-L181
```
bence@bh-macbook-macos ~/D/l/j/slonik-tools ((@slonik/migrator@0.9.1))> docker compose down
[+] Running 2/2
⠿ Container slonik-tools-postgres-1  Removed                                                                                                                                                                                                            0.2s
⠿ Network slonik-tools_default       Removed …
```
=> Fix hash function

jest.config.js, packages/typegen/src/query/column-info.ts, packages/typegen/test/options.test.ts
This fixes a bug, where this query
```sql
select count(*) as cnt
```
would return mistakenly return this type:
```typescript
cnt: number | null;
```
Count is guaranteed to be not null - from the [PSQL Docs](https://www.postgresql.org/docs/9.2/functions-aggregate.html):
> It should be noted that except for count, these functions return a null value when no rows are selected.
Tests were added to confirm.
Note: The change in jest.config.js is due to the fact that `jest --watch` was unusable, because every fixture render kept restarting the test(s).
=> fix(nullability): non-nullability of aliased count aggregation

packages/typegen/package.json, packages/typegen/src/index.ts, packages/typegen/src/query/parse.ts, yarn.lock
This updates all minor deps and `pqgsql-ast-parser`.
Two small changes were needed:
1. [chokidar 3.5.3](https://github.com/paulmillr/chokidar/releases/tag/3.5.3) now uses stricter types for ignore (see https://github.com/paulmillr/chokidar/pull/1140). It broke, because a readonly array couldn't be assigned to a regular array. This was fixed using a temporary workaround. I intend to address the glob/ignore/since logic in an upcoming pr.
2. [pgsql-ast-parser 10.0.2](https://github.com/oguimbal/pgsql-ast-parser) added a new operator, which was added as `'AT TIME ZONE': 'at_time_zone'`
`find-up` and `execa` were left untouched, even though updates are available.
This is because their last breaking change (v6) was updating pure ESM respectively.
This is still rather shaky for jest and also …
=> chore(deps): update dependencies

packages/typegen/src/index.ts, packages/typegen/test/limitations.test.ts
It was possible to make `psql` accidentally execute statements if they ended with a semicolon. The problem:
```
echo 'create table foo1(id int); \gdesc' | psql -f -
```
Actually _executes_ `create table foo(id int)` and ignores the `\gdesc` part as an invalid command. This works around by banning semicolons altogether unless they're the last character, in which case they'll be trimmed. Parsing the query would probably be better but it's harder to be sure it's safe that way.
=> fix(typegen): don't let semicolons cause queries to be executed

packages/typegen/src/write/prettify.ts, packages/typegen/src/write/sql.ts
This fixes https://github.com/mmkal/slonik-tools/issues/379
It seems typescript >4.2 doesn't like `const x = new Map<string, string>()` when using `createSourceFile`, for details see issue.
This is an easy workaround.
=> fix(tsPrettify): Error when processing .sql files

packages/typegen/readme.md
combined config and CLI options into one table
=> chore(readme): restructure config info

packages/demo/migrate.js, packages/migrator/readme.md, packages/migrator/src/index.ts, packages/migrator/test/pretty-logger.test.ts
Add exported prettyLogger object which converts log objects to strings and outputs them to console. Update incorrect default logger value. Fixes #408.
=> Add prettyLogger to migrator

packages/typegen/src/index.ts, packages/typegen/src/query/column-info.ts, packages/typegen/src/query/getViewResult.ts, packages/typegen/src/query/parse.ts
=> improve type extraction

packages/migrator/src/migrator.ts
connectionString is a URL, so it should be treated as such. regex didn't
handle more complex cases (such as "-" in the name of database).
And while it is possible to tweak regex for greater compatibility, using
actual URL-object guarantees proper result in ALL cases.
#434
=> 🐛 Use URL instead of regex for shadow-db name

packages/client/readme.md, packages/client/src/sql.ts, packages/client/src/types.ts, packages/client/test/__snapshots__/api-usage.test.ts.snap, packages/client/test/__snapshots__/slonik23.test.ts.snap, packages/client/test/__snapshots__/slonik37.test.ts.snap, packages/client/test/api-usage.test.ts, packages/client/test/edge-cases.test.ts, packages/client/test/slonik23.test.ts, packages/client/test/slonik37.test.ts
Re: #438 
@caoer first commit 46880bcca446730e366a6c64d9e7df1f3c3aa89b just adds a test which will fail - this is the bug you found. Second commit will be a fix.
Update: failed as expected, see screenshot below.
Fix in 16d94c2f1159226c76b7fa9a58509298cc477cf6 - haven't run the full suite but let's see.
=> test: reproduce nested sql bug

packages/client/package.json, packages/client/src/errors.ts, packages/client/src/sql.ts, packages/client/src/standard-schema/contract.ts, packages/client/src/standard-schema/errors.ts, packages/client/src/standard-schema/utils.ts, packages/client/src/types.ts, packages/client/test/api-usage.test.ts, packages/client/test/snapshots.ts, packages/client/test/zod.test.ts, packages/typegen/package.json, pnpm-lock.yaml
Simplifies code by removing `ZodEsque...` types etc. (more code is added, but it's just copy-paste from standard-schema).
This also copies zod's pretty error printer so we can pretty reliably get nice looking errors from pretty much any standard-schema library. (Or rather, my modification of zod's error printer): https://github.com/standard-schema/standard-schema/issues/84
=> Support any standard-schema in `sql.type`

packages/client/src/sql.ts, packages/client/test/bugs.test.ts
Whenever I go to this switch statement I find it hard to remember what's going on with all the `param.args[0]` and `param.args[1]` stuff. Each token type has a pretty different form, so this gives the `param.args` tuple members variables with names.
=> chore: sqlFnInner readability

packages/schemainspect/src/pg/obj.ts
The function `get_dependency_by_signature` may return undefined if none of the things match the given signature.
Filter out those undefined dependencies so that migra doesn't crash out completely.
Steps to reproduce
---
The simplest repro is to create the following view on supabase.
```sql
CREATE OR REPLACE VIEW "public"."users" AS
SELECT * FROM "auth"."users" "o"
WHERE ("o"."id" = "auth"."uid"());
```
Then run migra on the same database.
```ts
import { createClient } from "@pgkit/client";
import { Migration } from "@pgkit/migra";
const dbURL = "postgres://..."
const clientBase = createClient(dbURL);
const clientHead = createClient(dbURL);
const m = await Migration.create(clientBase, clientHead, {});
m.add_all_changes(true);
console.log(m.sql);
```
=> fix: remove undefined dependencies
